// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmttW4nX7TCpgnlEFUOL2Bt3_DHobKaN4',
    appId: '1:1071759737414:web:7643792b5973627c348047',
    messagingSenderId: '1071759737414',
    projectId: 'testingdata-d2cea',
    authDomain: 'testingdata-d2cea.firebaseapp.com',
    storageBucket: 'testingdata-d2cea.appspot.com',
    measurementId: 'G-Q8ECS72DWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsxA1NV32Os0UhqstoDzQS7mQN1bC8jn0',
    appId: '1:1071759737414:android:4f6f7a1552a1c967348047',
    messagingSenderId: '1071759737414',
    projectId: 'testingdata-d2cea',
    storageBucket: 'testingdata-d2cea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDccHMPYnC7AJcwFM4z_mvuW3FwuuEUUck',
    appId: '1:1071759737414:ios:562d7b902e88e21b348047',
    messagingSenderId: '1071759737414',
    projectId: 'testingdata-d2cea',
    storageBucket: 'testingdata-d2cea.appspot.com',
    androidClientId: '1071759737414-4qdrd9rei818fopqsl3lcfms8iegjfbv.apps.googleusercontent.com',
    iosClientId: '1071759737414-m3d1l8cnnemlvl57r9l83957iisbc0vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationTestapp',
  );
}
